<?php
 $languages = $block->getInitLanguagesList();
?>
<div class="language-list-container">
    <ul class="language-list">
        <?php foreach ($languages as $code => $language): ?>
            <li class="language-item" data-language-code="<?php echo $code; ?>">
                <img src="<?php echo $block->getViewFileUrl('Bss_ThemeDesign::images/' . $language['flag']); ?>" alt="<?php echo $language['name']; ?>" class="language-flag">
                <div class="language-name"><?php echo $code; ?></div>
                <div class="icon-isolation"><svg xmlns="http://www.w3.org/2000/svg" id="Isolation_Mode" data-name="Isolation Mode" viewBox="0 0 24 24" width="15" height="15"><path d="M21,16H16v5H3V3.409A.41.41,0,0,1,3.409,3H15.172l3-3H3.409A3.413,3.413,0,0,0,0,3.409V24H18.349L24,18.348V5.829l-3,3Z"/><path d="M5,19H8L23.4,3.6a2.121,2.121,0,0,0-3-3L5,16Z"/></svg></div>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<style>
    .language-list-container {
        margin: 20px 0;
    }

    .language-list {
        list-style: none;
        padding: 0;
        display: flex;
        flex-wrap: wrap;
    }

    .language-item {
        width: calc(20% - 20px);
        margin-right: 20px;
        margin-bottom: 20px;
        display: flex;
        justify-content: space-between;
        text-align: center;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px 10px;
        box-sizing: border-box;
        cursor: pointer;
    }

    .language-flag {
        width: 40%;
        height: 60px;
        border-radius: 5px;
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    }

    .language-name {
        font-size: 14px;
        color: #555;
    }

    .icon-isolation {
        padding-top: 2px;
    }
</style>

<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('.section-config').hide().first().show();
            $('.language-item').click(function() {
                $('.language-item').css('border-color', 'initial');
                $(this).css('border-color', '#eb5202');
                var languageCode = $(this).data('language-code');
                var translationId = 'languages_translation_list_' + languageCode;

                $('.section-config').hide().first().show();
                $('#' + translationId).show();
                $('#' + translationId).closest('.section-config').addClass('active').show();
            });
        });
    });
</script>
